trigger:
- master

pool: MyPC

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    npm run test-ci
    npm build
  displayName: 'npm install and build'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'juandifs00'
    scannerMode: 'CLI'
    configMode: 'file'

- task: SonarCloudAnalyze@1
  displayName: 'run SonarCloud'

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'